import lörem from "loerem";
import * as ö from 'ouml';

const words = {
	"adjective1": [
		"Key",
		"Main",
		"Chief",
		"Head",
		"", "", "", "", "", ""
	],
	"adjective2": [
		"Executive",
		"Senior",
		"Regional",
		"Associate",
		"Head",
		"Global",
		"Independent",
		"",
		"Division",
		"National",
		"Creative",
		"Dedicated",
		"Operations",
		"Area",
		"Licenced",
		"Retail",
		"Office",
		"Industrial",
		"International",
		"Deputy"
	],
	"adjective3": [
		"Executive",
		"Development",
		"Technical",
		"Business",
		"Financial",
		"IT",
		"Project",
		"Cost",
		"Managing",
		"Commercial",
		"Procurement",
		"Team",
		"Real Estate",
		"Sales",
		"Property",
		"Asset",
		"Facility",
		"Creative",
		"Operation",
		"Enterprise",
		"Corporate",
		"Green Building",
		"Construction",
		"Marketing",
		"Investment",
		"Customer",
		"Reconciliation",
		"Master",
		"Safety",
		"Process",
		"Research",
		"Leasing",
		"Strategy",
		"Planning",
		"Due Diligence",
		"Loan",
		"Risk",
		"Valuations",
		"Insurance",
		"Debt",
		"Portfolio",
		"Acquisitions",
		"Performance",
		"Economic",
		"Tax",
		"HR",
		"Hospitality",
		"Residential",
		"Infrastructure",
		"F&B"
	],
	"position": [
		"Director",
		"Manager",
		"Architect",
		"Representative",
		"Specialist",
		"President",
		"Vice-president",
		"Partner",
		"Engineer",
		"Officer",
		"Analyst",
		"Consultant",
		"Advisory",
		"Supervisor",
		"Executive",
		"Agent",
		"Economist",
		"Controller",
		"Counsel",
		"Researcher",
	]
}

export const title = () => `${words.adjective1[ö.random(words.adjective1.length)]} ${words.adjective2[ö.random(words.adjective2.length)]} ${words.adjective3[ö.random(words.adjective3.length)]} ${words.position[ö.random(words.position.length)]}`;

const suffix = [
	"Association",
	"Co.",
	"AG",
	"AB",
	'Group',
	"Corporation",
	"Corp.",
	"Foundation",
	"Fund",
	"Incorporated",
	"Inc.",
	"Institute",
	"Ltd.",
	"Society",
	"Syndicate",
	"Union",
	"LLC"
]

export const corporation = () => `${lörem({
	maxSentenceLength: 2,
	sentencesPerParagraph: 1,
	isHeadline: true,
	buzzFrequency: .5,
	useLörem: false,
	punchline: '',
})} ${suffix[ö.random(suffix.length)]}`
	.replace(
		/[\wåäöÅÄÖ]\S*/g,
		function (txt) {
			return txt.charAt(0).toUpperCase() + txt.substr(1);
		}
	)